### PR TITLE
add `release-notes` output

### PR DESCRIPTION
**Pull request by nbusseneau**
Add a new `release-notes` output to the action containing the release notes for the newly released versions, allowing consumers to leverage it in their workflows (e.g. by passing it down to the GitHub Release API).

Closes: #27

### CODE REVIEW

**Comment by nbusseneau** [comment]
## Important

I could not get `npm run build` to run because of npm dependency hell shenanigans:

```
ERROR in index.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
```

I spent 15 minutes trying to fix this mess and then remembered why I never wanted to touch these shenanigan ever again, so `dist/index.js` has NOT been updated as part of this PR. Big sorry, I hope you can make it work on your end.

`npm run test` does work fine though, here's the output with the new tests:
```
 PASS  __tests__/updateChangelog.test.ts
  √ should update empty_release changelog (22ms)
  √ should update standard changelog (4ms)                                                                                                                
  √ should update first_release changelog (2ms)                                                                                                           
  √ should update lowercase_link_reference changelog (4ms)                                                                                                
  √ should update tag_release changelog (3ms)                                                                                                             
  √ should update tag_on_tag changelog (3ms)                                                                                                              
                                                                                                                                                          
 PASS  __tests__/getReleaseNotes.test.ts                                                                                                                  
  √ should extract empty_release release-notes output (3ms)
  √ should extract standard release-notes output (3ms)                                                                                                    
  √ should extract first_release release-notes output (1ms)                                                                                               
  √ should extract lowercase_link_reference release-notes output (2ms)                                                                                    
  √ should extract tag_release release-notes output (2ms)                                                                                                 
  √ should extract tag_on_tag release-notes output (2ms)                                                                                                  
                                                                                                                                                          
 PASS  __tests__/getGenesisHash.test.ts                                                                                                                   
  √ should return a hash (46ms)
                                                                                                                                                          
 PASS  __tests__/getInputs.test.ts                                                                                                                        
  √ version or tag is required (4ms)
  √ tag is used before version (1ms)                                                                                                                      
  √ version fallback works (1ms)                                                                                                                          
  √ can parse prefixed tag                                                                                                                                
  √ date is optional but has a default                                                                                                                    
  √ parses date into ISO8601                                                                                                                              
  √ parses GITHUB_REPOSITORY into owner and repo                                                                                                          
  √ can handle ISO8601 date (1ms)                                                                                                                         
  √ changelog path is optional but has a default                                                                                                          
  √ parse changelog path from input                                                                                                                       
                                                                                                                                                          
 PASS  __tests__/formatDate.test.ts                                                                                                                       
  √ should format 'Dec 09 2019' as '2019-12-09'
  √ should format 'Dec 16 2019' as '2019-12-16' (1ms)                                                                                                     
  √ should format 'Jan 09 2019' as '2019-01-09'                                                                                                           
                                                                                                                                                          
Test Suites: 5 passed, 5 total                                                                                                                            
Tests:       26 passed, 26 total                                                                                                                          
Snapshots:   0 total
Time:        1.188s
Ran all test suites.
```

**Comment by thomaseizinger** [comment]
> I spent 15 minutes trying to fix this mess and then remembered why I never wanted to touch these shenanigans ever again, so `dist/index.js` has NOT been updated as part of this PR. Big sorry, I hope you can make it work on your end.

We need to update that if we want to use this feature though!

Unfortunately, GitHub cannot natively execute TS in its actions and it is always the compiled JS that gets executed.

**Comment by thomaseizinger** [comment]
> I could not get `npm run build` to run because of npm dependency hell:

This is a `yarn` project but `yarn run build` also fails for me locally. This is madness, how can this fail if we have a lockfile? I don't really have the time to dig into it sorry :(

**Comment by thomaseizinger** [comment]
Apparently it is an issue with an outdated Node version, so perhaps a dependency upgrade can fix it?

https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e

**Comment by nbusseneau** [comment]
> Apparently it is an issue with an outdated Node version, so perhaps a dependency upgrade can fix it?
> 
> https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e

Yea this what I tried to do initially but gave up when I saw the mess, I honestly don't want to ever again touch anything like that, I've been `npm`-free for years now...!

**Comment by nbusseneau** [comment]
OK I bit the bullet and decided to go the full stupid route: I downgraded Node to v16.20.2 (instead of using the latest LTS like any sane person would do), and I can now run `yarn build`.

**Comment by nbusseneau** [comment]
Tests are still passing:

```console
> yarn test
yarn run v1.22.22
$ jest
 PASS  __tests__/updateChangelog.test.ts
  √ should update empty_release changelog (16ms)
  √ should update standard changelog (4ms)                                                                                                                                    
  √ should update first_release changelog (2ms)                                                                                                                               
  √ should update lowercase_link_reference changelog (3ms)                                                                                                                    
  √ should update tag_release changelog (4ms)                                                                                                                                 
  √ should update tag_on_tag changelog (3ms)                                                                                                                                  
                                                                                                                                                                              
 PASS  __tests__/getGenesisHash.test.ts                                                                                                                                       
  √ should return a hash (40ms)
                                                                                                                                                                              
 PASS  __tests__/getReleaseNotes.test.ts                                                                                                                                      
  √ should extract empty_release release-notes output (4ms)
  √ should extract standard release-notes output (2ms)                                                                                                                        
  √ should extract first_release release-notes output (2ms)                                                                                                                   
  √ should extract lowercase_link_reference release-notes output (1ms)                                                                                                        
  √ should extract tag_release release-notes output (2ms)                                                                                                                     
  √ should extract tag_on_tag release-notes output (2ms)                                                                                                                      
                                                                                                                                                                              
 PASS  __tests__/getInputs.test.ts                                                                                                                                            
  √ version or tag is required (6ms)
  √ tag is used before version                                                                                                                                                
  √ version fallback works (1ms)                                                                                                                                              
  √ can parse prefixed tag                                                                                                                                                    
  √ date is optional but has a default                                                                                                                                        
  √ parses date into ISO8601 (1ms)                                                                                                                                            
  √ parses GITHUB_REPOSITORY into owner and repo                                                                                                                              
  √ can handle ISO8601 date                                                                                                                                                   
  √ changelog path is optional but has a default                                                                                                                              
  √ parse changelog path from input                                                                                                                                           
                                                                                                                                                                              
 PASS  __tests__/formatDate.test.ts                                                                                                                                           
  √ should format 'Dec 09 2019' as '2019-12-09'
  √ should format 'Dec 16 2019' as '2019-12-16'                                                                                                                               
  √ should format 'Jan 09 2019' as '2019-01-09'                                                                                                                               
                                                                                                                                                                              
Test Suites: 5 passed, 5 total                                                                                                                                                
Tests:       26 passed, 26 total                                                                                                                                              
Snapshots:   0 total
Time:        1.083s
Ran all test suites.
::warning::Version argument will be deprecated soon, use tag instead.
Done in 1.67s.
```

**Review by thomaseizinger — APPROVED** [review]
Sorry for the delay! Thank you for the contribution :)

**Comment by thomaseizinger** [comment]
You should be able to depend on latest `main` now and use this. Let me know how that goes. I can make a release then :)

**Comment by nbusseneau** [comment]
OK I'll probably release something in the next couple days, will let you know.

**Comment by nbusseneau** [comment]
It works fine. Here's an example of a successful run using `@master`: https://github.com/nbusseneau/LotusEcarlateChanges/actions/runs/10057749177/job/27799379670

Relevant tidbits:
- https://github.com/nbusseneau/LotusEcarlateChanges/actions/runs/10057749177/workflow#L37-L41
- https://github.com/nbusseneau/LotusEcarlateChanges/actions/runs/10057749177/workflow#L64

Result: https://github.com/nbusseneau/LotusEcarlateChanges/releases/tag/0.6.40

**Comment by thomaseizinger** [comment]
Awesome, thanks! Will release tomorrow.

**Comment by thomaseizinger** [comment]
Released: https://github.com/thomaseizinger/keep-a-changelog-new-release/releases/tag/3.1.0.

**Comment by baynezy** [comment]
@thomaseizinger / @nbusseneau do we as users need to do anything to take advantage of this?

**Comment by thomaseizinger** [comment]
> @thomaseizinger / @nbusseneau do we as users need to do anything to take advantage of this?

I am not sure I understand your question? Starting with this PR, the action emits an output called `release-notes`. What you do with that is up to you. If you want to to show up in a GitHub release, you can use the output as part of creating your release.

See @nbusseneau's workflow file: https://github.com/nbusseneau/LotusEcarlateChanges/actions/runs/10057749177/workflow#L64

**Comment by baynezy** [comment]
@thomaseizinger - sorry I understand now.

**Pull request merged**
